type attackType = {
  name: string;
  bonus: string;
  damage: string;
};

export type CharSheetType = {
  charName: string;
  classnLevel: string;
  background: string;
  playerName: string;
  race: string;
  alignment: string;
  exp: string;
  inspiration: string;
  proficiencyBonus: number;
  strength: number;
  dexterity: number;
  constitution: number;
  intelligence: number;
  wisdom: number;
  charisma: number;
  armorClass: string;
  initiative: string;
  speed: string;
  maxHp: string;
  currentHp: string;
  tempHp: string;
  totalHitDice: string;
  hitDice: string;
  personalityTraits: string;
  ideals: string;
  bonds: string;
  flaws: string;
  attacksAndSpellcasting: string;
  featuresAndTraits: string;
  equipmentAndNotes: string;
  otherProfsAndLangs: string;
  attack1: attackType;
  attack2: attackType;
  attack3: attackType;
  success1: boolean;
  success2: boolean;
  success3: boolean;
  fail1: boolean;
  fail2: boolean;
  fail3: boolean;
  proficiencies: {
    strength: boolean;
    atletics: boolean;
    dexterity: boolean;
    constitution: boolean;
    intelligence: boolean;
    wisdom: boolean;
    charisma: boolean;
    acrobatics: boolean;
    animalHandling: boolean;
    arcana: boolean;
    athletics: boolean;
    deception: boolean;
    history: boolean;
    insight: boolean;
    intimidation: boolean;
    investigation: boolean;
    medicine: boolean;
    nature: boolean;
    perception: boolean;
    performance: boolean;
    persuasion: boolean;
    religion: boolean;
    sleightOfHand: boolean;
    stealth: boolean;
    survival: boolean;
  };
};

export const initialCharSheet: CharSheetType = {
  charName: "",
  classnLevel: "",
  background: "",
  playerName: "",
  race: "",
  alignment: "",
  exp: "",
  inspiration: "",
  proficiencyBonus: 0,
  strength: 10,
  dexterity: 10,
  constitution: 10,
  intelligence: 10,
  wisdom: 10,
  charisma: 10,
  armorClass: "",
  initiative: "",
  speed: "",
  maxHp: "",
  currentHp: "",
  totalHitDice: "",
  tempHp: "",
  hitDice: "",
  personalityTraits: "",
  ideals: "",
  bonds: "",
  flaws: "",
  attacksAndSpellcasting: "",
  featuresAndTraits: "",
  equipmentAndNotes: "",
  otherProfsAndLangs: "",
  success1: false,
  success2: false,
  success3: false,
  fail1: false,
  fail2: false,
  fail3: false,
  attack1: {
    name: "",
    bonus: "",
    damage: "",
  },
  attack2: {
    name: "",
    bonus: "",
    damage: "",
  },
  attack3: {
    name: "",
    bonus: "",
    damage: "",
  },
  proficiencies: {
    strength: false,
    dexterity: false,
    constitution: false,
    intelligence: false,
    wisdom: false,
    charisma: false,
    atletics: false,
    acrobatics: false,
    animalHandling: false,
    arcana: false,
    athletics: false,
    deception: false,
    history: false,
    insight: false,
    intimidation: false,
    investigation: false,
    medicine: false,
    nature: false,
    perception: false,
    performance: false,
    persuasion: false,
    religion: false,
    sleightOfHand: false,
    stealth: false,
    survival: false,
  },
};
